knowage:
    image: coolersport/knowage-server-docker:6.4.0
    links:
        - knowagedb:db
    ports:
        - "8080:8080"
    environment:
        - WAIT_MYSQL=true

knowagedb:
    image: mysql:5.7
    environment:
        - MYSQL_USER=knowageuser
        - MYSQL_PASSWORD=knowagepassword
        - MYSQL_DATABASE=knowagedb
        - MYSQL_ROOT_PASSWORD=knowagerootpassword
